### ISSUE TITLE
Double encoding in `duckpan publisher`

### ISSUE THREAD

**Issue by jbarrett** [duckduckgo/duckduckgo-publisher#210]
Appears to effect donttrackus only

![](http://jbrt.org/ddg/double_encoding.png)

**Comment by moollaza** [comment]
The issue is likely inside https://github.com/duckduckgo/p5-app-duckpan. Specifically in https://github.com/duckduckgo/p5-app-duckpan/blob/master/lib/App/DuckPAN/WebPublisher.pm

There's some UTF8 code in place -- but it's likely incorrect: https://github.com/duckduckgo/p5-app-duckpan/blob/master/lib/App/DuckPAN/WebPublisher.pm#L93

/cc @zachthompson

**Comment by moollaza** [comment]
@jbarrett I just noticed that you mentioned it only affects 1 domain. That's odd...

**Comment by jbarrett** [comment]
Yeah, we have lots of weirdly specific Unicode handling all over the place. That line certainly looks suspect. Very weird indeed that it only effects one domain.

Decode incoming, encode outgoing. Anything else is a footnote[0]

[0] a long and winding footnote with many corners and caveats.
